### ISSUE TITLE
Write documentation section 1: Introduction and goals

### ISSUE THREAD

**Issue by laura-pb** [Arquisoft/dede_en2b#10]
Write the first part of the documentation: Introduction and goals.
This section is divided in three parts: requirements overview, quality goals and stakeholders.

**Comment by UO277653** [comment]
In order to help us identify the most important quality goals, we would like to know what @pglez82, as a a stakeholder of this software system, prioritizes the most, in order to focus on those ones during the development process. After analyzing the assignment, it suggests that privacy is among the most relevant, as it is a requirement to follow the SOLID principles. Other major ones would be, for example, availability (we should be able to use the system at all times), security (we have to guarantee that the system is protected against malicious attacks), usability (the system should be able to be used in several ways) and performance, but we would like to take into account the opinion of the stakeholders before prioritizing this qualities ourselves.

**Comment by pglez82** [comment]
Hi,

All the quality goals that you have mentioned are important. For the assignment, I think privacy, usability and performance will be among the most important for me if I have to prioritize some (note that this is just my opinion). Privacy because the assignment focus on that with the use of SOLID, and usability and performance because in my experience, when the day comes and you present your work, they are two properties that makes very easy for the clients (the teachers), to test your software and really appreciate the work that you have done. There have been teams in previous courses that did a very good work but it got eclipsed because of a bad usability or performance in their applications.

I hope this helps.

Pablo

**Comment by UO277653** [comment]
I have another doubt, this time regarding the stakeholders, in the theory slides the structure of the table of section 1.3 is 

| Stakeholder | Description | Expectations

But in the template of the Arc42 documentation it is

| Stakeholder | Contact | Expectations

Which one should we follow?

**Comment by pglez82** [comment]
Template can be modified. If in the table the description of the stakeholder is relevant it can be added without any further issues.
