### ISSUE TITLE
Https

### ISSUE THREAD

**Issue by DiegoMfer** [Arquisoft/dede_en2b#128]

**Comment by DiegoMfer** [comment]
Hello, I have a problem when trying to get a SSL certificate, I need this for changing the domain name and for having an https connection:
![image](https://user-images.githubusercontent.com/79276285/164042004-085b8034-a413-4487-ba5d-c70601f7e52e.png)

**Comment by UO277653** [comment]
It is possible that the problem that we had with the inrupt login is caused by this

**Comment by pglez82** [comment]
It is possible that you do not have permissions for that. A possible solution is to use this service:

https://letsencrypt.org/

I have used it in the past and it works very well, and it is easy to set up having access to the machine console (which you have).

Pablo

**Comment by UO277653** [comment]
Hello, we have seen that AWS gives us the option to use the 443 port in order to connect the deployed machine, but for some reason even after changing the port from 3000 to 443 in the docker files it is not connecting to the page.

**Comment by pglez82** [comment]
Have you opened the port in the AWS network configuration?

**Comment by UO277653** [comment]
Now I have tried with Let's Encrypt, but I got the following error

![imagen](https://user-images.githubusercontent.com/79276201/165355395-611e4817-78fd-4ac3-b00f-e14bffa7c1df.png)

I have made sure that port 80 is open, but still it does not let me create the certificate

**Comment by pglez82** [comment]
Would need to see the file /var/log/letsencrypt/letsencrypt.log

**Comment by UO277653** [comment]
![imagen](https://user-images.githubusercontent.com/79276201/165364639-94777e47-fa55-4b17-b9a9-accbb38cae0d.png)
![imagen](https://user-images.githubusercontent.com/79276201/165364661-50832aea-0839-42a6-b9c6-8be132750369.png)
![imagen](https://user-images.githubusercontent.com/79276201/165364684-0d52cfbf-4c28-4601-aacd-8955f88e0acb.png)
![imagen](https://user-images.githubusercontent.com/79276201/165364712-79d50c97-8f01-4501-ae06-33f31de52efc.png)
![imagen](https://user-images.githubusercontent.com/79276201/165364747-cca5c76d-d6b9-4406-bf46-4906c043d99e.png)
![imagen](https://user-images.githubusercontent.com/79276201/165364781-71f26229-b6c4-4a87-a9ad-76988b43e442.png)
![imagen](https://user-images.githubusercontent.com/79276201/165364804-a18d5c1a-abff-42e0-8a29-74f08dfbed2c.png)

These are the contents

**Comment by pglez82** [comment]
The first thing. It is easier to send the actual file, not screenshots. To access a remote file you can use any sftp client to access the files over ssh.

The error that I can see is that you need to have the 80 port free. Right now you have the website running in http://dedeen2b.tk/ so you would need to stop that before running letencrypt in the server. Let encrypt needs to run its own web server in this port to verify that you own the machine.

**Comment by UO277653** [comment]
But if I stop http://dedeen2b.tk/ how could I run Let's Encrypt if it uses a domain name and not IP?

**Comment by UO277653** [comment]
I have also tried using a reverse-proxy like Caddy, but it did not work either, I am honestly quite lost at this point

**Comment by pglez82** [comment]
Ok. First you need to understand how let encrypt works. In order to issue a certificate for your server, let encrypt needs to guarantee that you own the domain and the server. For that, he asks you the domain and ask you to run a software in the server that will listen in port 80 (for that, the port should be free). When the software is running they verify that they can connect to port 80. This only the verification process. After the verification is done, and the certificate is created, you can put back your service in port 80. So, what you have to do is, stop your webapp in the aws machine, make sure the domain is pointing to your machine ip, and run the letsencrypt software so it can make the verification. When you have the certificate I think is valid for 3 or 4 months so you do need to care about this anymore.

**Comment by pglez82** [comment]
> But if I stop http://dedeen2b.tk/ how could I run Let's Encrypt if it uses a domain name and not IP?

Is not stopping the domain but stopping the webapp running in aws.

**Comment by pglez82** [comment]
What is the status on this issue?

**Comment by UO277653** [comment]
Today (yesterday we could not do it due to some work of other assignments) we are going to try to generate the certificate on the Azure machine in order for the page to be HTTPS. In case we have some problem with that we will probably post it here.

**Comment by UO277653** [comment]
Hello, we have created a certificate in Azure, how could we add it to the website?

**Comment by DiegoMfer** [comment]
We have created the certificate for the website, the problem is that we dont know how to add it so https is connected. The tutorials that we find are for webservers and we are a bit lost. What would be the next step to do? Thanks in advance.

**Comment by UO277653** [comment]
Update:

We have successfully generated the certificate with Let's Encrypt

![imagen](https://user-images.githubusercontent.com/79276201/165837538-83295e36-29b4-40c8-be99-6f083d751465.png)

All the problems were happening because in the domain provider we did not have the DNS configured correctly

![imagen](https://user-images.githubusercontent.com/79276201/165837627-6c47ae73-f802-402d-85bf-2676eb94889d.png)

Now we have to redirect the traffic from port 80 or 443 to the port 3000 for the webapp

**Comment by UO277653** [comment]
Sorry for the spam

We have used Caddy in order to redirect the traffic, with that everything works

![imagen](https://user-images.githubusercontent.com/79276201/165839842-207ab12e-c5b7-4370-bead-fc324ffb7a1c.png)

The login as well.

The only "problem" is that everytime we want to use the machine without problem we have to use docker-compose up and caddy run, I am not sure if this can be automated. Either way the deployed run is running OK now. Thanks and sorry for the inconvenience.
