### ISSUE TITLE
Implement a login mechanism

### ISSUE THREAD

**Issue by laura-pb** [Arquisoft/dede_en2b#54]
The user will login directly with their POD identity.

**Comment by UO277653** [comment]
Hello, @pglez82 , we have the login mechanism finished, but we are having some trouble when accessing the address of the user, the information cannot be accessed. In order to get the address, we would need to access this link:

![imagen](https://user-images.githubusercontent.com/79276201/158058129-3d1e2c85-14f3-4ce8-b093-3b53c6e12702.png)

Which is provided by the hasAddress property

![imagen](https://user-images.githubusercontent.com/79276201/158058147-4c457328-92e2-40a9-bde5-d89dbdea796d.png)

And that one, in theory, should return the value without any issue, but it does not work. After trying several different methods, and consulting the documentation of Inrupt, we still cannot access the address, and we would like to know if there is something we can do to solve this issue.

**Comment by pglez82** [comment]
Maybe this example can sort things out for you:

https://solid-ui-react.docs.inrupt.com/?path=/story/components-table--nested-data-example

It is about accessing nested information (like the address). From lines 230 to 330 you have an example of how to access the telephone (it is similar for the address). Note that the example uses @inrupt/solid-client, that is the library to use for doing these nested queries.

Pablo
